"""
eval/build_adaptive_hybrid.py
─────────────────────────────
Derive the hybrid (P3 picker-corridor + P2 storage-depot) charging config for
ANY warehouse grid, scaled to fleet size: |C| = round(rho * N), rho in [0.5,0.6]
(the dimensionless saturation-knee / survivorship-floor band found in the study).

Picker cells are derived from the grid's actual picking stations via the
grid-adaptive P3 pipeline (find_picking_stations); the remaining budget is filled
with P2 affinity-propagation depot exemplars. Output is the same format as
final_solution/charging_config.json (pipeline 3, selective, explicit
charger_positions) plus the validated policy (18/60/50, corrected energy).

This is the 'PREDICT' step of predict-then-confirm: it produces a *candidate*
config for a new grid. It is NOT a validated solution there until a confirmation
simulation run is done (see the deployment protocol, paper Sec. Deploying-to-a-
different-warehouse).

    python eval/build_adaptive_hybrid.py --n 20 --rho 0.6 \
        --grid generated_pod.csv --out charging_config.json
"""
from __future__ import annotations
import sys, json, csv, argparse
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parents[2]   # scripts/data/<file> -> repo root
sys.path.insert(0, str(ROOT))
from model.charging_layout_generator import ChargingLayoutGenerator

POLICY = {"battery_low_pct": 18, "battery_charged_pct": 60,
          "battery_interrupt_pct": 50, "corrected_energy_model": True}


def load_grid(path) -> np.ndarray:
    rows = []
    with open(path, newline="") as f:
        for r in csv.reader(f):
            rows.append([int(x) for x in r])
    return np.array(rows, dtype=int)


def build(grid: np.ndarray, n_robots: int, rho: float = 0.6):
    """Return (config dict, n_picker_cells, n_depot_cells)."""
    budget = max(1, round(rho * n_robots))

    # P3: picker-corridor cells derived from the grid's picking stations.
    g3 = ChargingLayoutGenerator(grid.copy(), {
        "pipeline": 3, "num_chargers": budget, "selective_picker_chargers": True})
    g3.generate()
    p3 = [[int(p[0]), int(p[1])] for p in g3.config.get("charger_positions", [])]

    # P2: affinity-propagation depots fill the remaining budget.
    m = max(0, budget - len(p3))
    p2 = []
    if m > 0:
        g2 = ChargingLayoutGenerator(grid.copy(), {
            "pipeline": 2, "num_chargers": m,
            "c": 1.0, "alpha": 1.0, "beta": 1.0, "gamma": 1.0})
        g2.generate()
        p2 = [[int(p[0]), int(p[1])] for p in g2.config.get("charger_positions", [])]

    seen, combined = set(), []
    for cell in p3 + p2:
        t = (cell[0], cell[1])
        if t not in seen:
            seen.add(t)
            combined.append(cell)

    cfg = {
        "_comment": "ADAPTIVE hybrid config (predict step) — regenerated by "
                    "eval/build_adaptive_hybrid.py for this grid + fleet size.",
        "pipeline": 3,
        "num_chargers": len(combined),
        "disable_active_charging": False,
        "selective_picker_chargers": True,
        **POLICY,
        "charger_positions": combined,
    }
    return cfg, len(p3), len(p2)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=20, help="fleet size N")
    ap.add_argument("--rho", type=float, default=0.6, help="|C|/N ratio (0.5-0.6)")
    ap.add_argument("--grid", default=str(ROOT / "generated_pod.csv"))
    ap.add_argument("--out", default=str(ROOT / "charging_config.json"))
    a = ap.parse_args()

    grid = load_grid(a.grid)
    cfg, n3, n2 = build(grid, a.n, a.rho)
    Path(a.out).write_text(json.dumps(cfg, indent=2))
    print(f"[adaptive] grid {grid.shape}  N={a.n}  rho={a.rho}  "
          f"|C|_target={round(a.rho * a.n)}  |C|_actual={cfg['num_chargers']}  "
          f"(P3 picker={n3}, P2 depot={n2})")
    print(f"[adaptive] wrote {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
