"""
scripts/data/build_charging_solution.py
──────────────────────────────────────────
Reproducibly regenerate the FINAL charging solution (hybrid 6/6, global,
policy 18/60/50) from the warehouse grid. The committed charging_config.json
in this folder is the authoritative artifact; this script documents HOW those
charger positions were derived and lets a teammate re-derive them on a
different grid.

Solution = 6 picker-corridor cells (P3, dwell-priority) + 6 storage-area
depot cells (P2, affinity-propagation exemplars), under GLOBAL active charging
(a low-battery robot may park-to-charge at ANY charger cell), with the
threshold policy tau_low=18 % / tau_full=60 % / interrupt@50 %.

Run from the repository root:
    python scripts/data/build_charging_solution.py
writes  data/input/charging/salsa_charging_config.json.

This only regenerates the parked configuration artifact; it does not enable
charging behavior in main_future.

Dependencies: model/charging_layout_generator.py (P2 affinity propagation) and
data/input/base/generated_pod.csv, both already in the shared repo.
"""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from model.charging_layout_generator import ChargingLayoutGenerator  # noqa: E402

OUT = ROOT / "data" / "input" / "charging" / "salsa_charging_config.json"
GRID = ROOT / "data" / "input" / "base" / "generated_pod.csv"

# ── Final, validated policy (Phase-2b RSM region + Phase-3 Taguchi robust) ──
POLICY = {"battery_low_pct": 18, "battery_charged_pct": 60,
          "battery_interrupt_pct": 50}

# Number of picker-corridor (P3) cells and storage-depot (P2) cells.
# 6/6 split Pareto-dominated every alternative at |C|=12 (3-seed validated).
K_P3 = 6
M_P2 = 6

# Canonical picker-tier cells in DWELL-PRIORITY order (highest value first):
# the 5 picker processing spots (one per station, col 2), then the queue-back
# cell of the busiest station (picker-1, col 4). Top-K_P3 are kept.
# Stored [row, col]; netlogo.py converts to (x=col, y=row).
P3_DWELL_PRIORITY = [
    [1, 2], [7, 2], [13, 2], [19, 2], [25, 2],   # 5 processing spots
    [3, 4],                                       # picker-1 queue-back (6th)
    [9, 4], [15, 4], [21, 4], [27, 4],            # remaining queue-backs
    [3, 3], [21, 3],                              # mid-queue (busiest stations)
]


def load_grid(path: Path) -> np.ndarray:
    rows = []
    with open(path, newline="") as f:
        for r in csv.reader(f):
            rows.append([int(x) for x in r])
    return np.array(rows, dtype=int)


def gen_p2_depots(grid: np.ndarray, m: int) -> list[list[int]]:
    """m affinity-propagation exemplar cells in the storage area (P2)."""
    cfg = {"pipeline": 2, "num_chargers": m,
           "c": 1.0, "alpha": 1.0, "beta": 1.0, "gamma": 1.0}
    g = ChargingLayoutGenerator(grid.copy(), cfg)
    g.generate()
    return [[int(p[0]), int(p[1])] for p in g.config.get("charger_positions", [])]


def main() -> int:
    grid = load_grid(GRID)
    p3 = [list(c) for c in P3_DWELL_PRIORITY[:K_P3]]
    p2 = gen_p2_depots(grid, M_P2)

    seen, combined = set(), []
    for cell in p3 + p2:
        t = (cell[0], cell[1])
        if t not in seen:
            seen.add(t)
            combined.append(cell)

    config = {
        "_comment": "FINAL charging solution — regenerated by "
                    "final_solution/build_charging_solution.py. "
                    "charger_positions are [row, col].",
        "pipeline": 3,
        "num_chargers": len(combined),
        "disable_active_charging": False,     # global: park-to-charge at any cell
        "selective_picker_chargers": True,    # only listed picker cells are chargers
        **POLICY,
        "charger_positions": combined,
    }
    OUT.write_text(json.dumps(config, indent=2))
    print(f"P3 picker cells ({len(p3)}): {p3}")
    print(f"P2 depot cells  ({len(p2)}): {p2}")
    print(f"total |C| = {len(combined)}  policy = {POLICY}")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
